name: Python versions

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: curl -sL https://install.python-poetry.org | python - -y
      - name: Install requirements
        run: poetry install
      - name: Run visualizers
        run: poetry run python -m tests.run
